[package]
name = "playground-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
aws-sdk-s3 = "0.5.2"
aws-config = "0.5.2"
tokio = { version = "1.13", features = ["full"] }
tracing = "0.1.29"
tracing-subscriber = "0.3.6"
